-- Little Strays accounts, preorders, and admin order export.
-- Run this SQL in your Supabase project's SQL editor after creating the project.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  pet_names text,
  delivery_address text,
  delivery_notes text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists delivery_address text;

alter table public.profiles
  add column if not exists is_admin boolean not null default false;

alter table public.profiles enable row level security;

create or replace function public.is_admin(user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = user_id
      and is_admin = true
  );
$$;

drop policy if exists "Profiles are viewable by owners" on public.profiles;
create policy "Profiles are viewable by owners"
  on public.profiles
  for select
  using ((select auth.uid()) = id or public.is_admin());

drop policy if exists "Profiles are insertable by owners" on public.profiles;
create policy "Profiles are insertable by owners"
  on public.profiles
  for insert
  with check ((select auth.uid()) = id);

drop policy if exists "Profiles are updateable by owners" on public.profiles;
create policy "Profiles are updateable by owners"
  on public.profiles
  for update
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_email text not null,
  customer_name text not null,
  phone text,
  delivery_address text not null,
  delivery_notes text,
  status text not null default 'new'
    check (status in ('new', 'processing', 'fulfilled', 'cancelled')),
  subtotal_cents integer not null check (subtotal_cents >= 0),
  delivery_cadence text not null default 'twice_monthly',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_slug text not null,
  product_name text not null,
  product_category text not null,
  product_image text not null,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  line_total_cents integer not null check (line_total_cents >= 0),
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Orders are viewable by owners and admins" on public.orders;
create policy "Orders are viewable by owners and admins"
  on public.orders
  for select
  using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "Orders are insertable by owners" on public.orders;
create policy "Orders are insertable by owners"
  on public.orders
  for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "Orders are deleteable by owners while new" on public.orders;
create policy "Orders are deleteable by owners while new"
  on public.orders
  for delete
  using ((select auth.uid()) = user_id and status = 'new');

drop policy if exists "Orders are updateable by admins" on public.orders;
create policy "Orders are updateable by admins"
  on public.orders
  for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Order items are viewable by order owners and admins" on public.order_items;
create policy "Order items are viewable by order owners and admins"
  on public.order_items
  for select
  using (
    exists (
      select 1
      from public.orders
      where orders.id = order_items.order_id
        and (orders.user_id = (select auth.uid()) or public.is_admin())
    )
  );

drop policy if exists "Order items are insertable by order owners" on public.order_items;
create policy "Order items are insertable by order owners"
  on public.order_items
  for insert
  with check (
    exists (
      select 1
      from public.orders
      where orders.id = order_items.order_id
        and orders.user_id = (select auth.uid())
    )
  );

drop policy if exists "Order items are deleteable by order owners while new" on public.order_items;
create policy "Order items are deleteable by order owners while new"
  on public.order_items
  for delete
  using (
    exists (
      select 1
      from public.orders
      where orders.id = order_items.order_id
        and orders.user_id = (select auth.uid())
        and orders.status = 'new'
    )
  );

create index if not exists orders_user_id_created_at_idx
  on public.orders (user_id, created_at desc);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_profiles_updated_at on public.profiles;
create trigger update_profiles_updated_at
  before update on public.profiles
  for each row
  execute function public.update_updated_at_column();

drop trigger if exists update_orders_updated_at on public.orders;
create trigger update_orders_updated_at
  before update on public.orders
  for each row
  execute function public.update_updated_at_column();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();
